### PR TITLE
Update worker.py

### PR DESCRIPTION
**Pull request by arvindsoni80**
Added a try/except to catch file not found error which currently kills the task

### CODE REVIEW

**Comment by mreferre** [comment]
Thanks @arvindsoni80 for the PR. This was something long overdue I wanted to fix. I noticed that now the behavior is to delete the SQS message in the queue even if the file is not find. I am wondering if the delete of the message from the queue should be tight to the move of the file. That is, the message in the queue should not be deleted if the message is not found.

**Comment by arvindsoni80** [comment]
> Thanks @arvindsoni80 for the PR. This was something long overdue I wanted to fix. I noticed that now the behavior is to delete the SQS message in the queue even if the file is not find. I am wondering if the delete of the message from the queue should be tight to the move of the file. That is, the message in the queue should not be deleted if the message is not found.

Yes. let me see.

**Comment by arvindsoni80** [comment]
> > Thanks @arvindsoni80 for the PR. This was something long overdue I wanted to fix. I noticed that now the behavior is to delete the SQS message in the queue even if the file is not find. I am wondering if the delete of the message from the queue should be tight to the move of the file. That is, the message in the queue should not be deleted if the message is not found.
> 
> Yes. let me see.

If we don't delete the message and simply add a `continue`, will it keep trying the same message? For this demo app seems ok to delete it even if file not found.

**Comment by mreferre** [comment]
On a second thought I think you are right. In theory the message would be put back into the queue and then it will be picked again (rinse and repeat). While in a production environment you may want to have better control of this flow I agree that for this demo deleting the message (regardless of whether the file was found or not) is the right thing to do. It just auto-clean up everything for you (and it leaves a message in the log that you can analyze further IF the file was not found).

**Pull request merged**
